Add unit tests for com.lrs.common.utils.encrypt.SHA
Diffblue-benchmarks/admin-plus pull request #1
Opened 2019-05-16 08:31 UTC by Braavos96

I've analysed your codebase and noticed that `com.lrs.common.utils.encrypt.SHA` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

2019-05-16 08:45 UTC, petersear requested changes

2019-05-16 08:45 UTC, petersear commented on admin-common/pom.xml
> +        <dependency>
The added dependency does not line up with those already in pom.xml.

2019-05-16 08:45 UTC, petersear commented on admin-common/pom.xml
> -	</dependencies>
Looks like this was indented correctly already(?)

2019-05-16 08:45 UTC, petersear commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        String retval = Base64.getEncoder().encodeToString((SHA.encryptSHA(data)));
line > 80 chars

2019-05-16 08:45 UTC, petersear commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +    public void testEncryptSHA() throws Exception {
Are the `throws` needed?

2019-05-16 08:58 UTC, Braavos96 commented on admin-common/pom.xml
> +        <dependency>
moved

2019-05-16 08:59 UTC, Braavos96 commented on admin-common/pom.xml
> -	</dependencies>
moved

2019-05-16 08:59 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        String retval = Base64.getEncoder().encodeToString((SHA.encryptSHA(data)));
altered

2019-05-16 09:00 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +    public void testEncryptSHA() throws Exception {
The method being tested throws and the test requires it. unhandled exception

2019-05-16 10:17 UTC, petersear requested changes
Looks better now that the white space issues have been resolved :-)

2019-05-16 10:17 UTC, petersear commented on admin-common/pom.xml
> +		<dependency>
testng dependency?

2019-05-16 10:17 UTC, petersear commented on admin-common/pom.xml
> +		<dependency>
JUnit dependency appears twice

2019-05-16 13:56 UTC, Braavos96 commented on admin-common/pom.xml
> +		<dependency>
Not sure how that got there :)

2019-05-16 13:56 UTC, Braavos96 commented on admin-common/pom.xml
> +		<dependency>
removed

2019-05-16 14:42 UTC, petersear approved these changes

2019-05-16 15:13 UTC, freddytuxworth requested changes

2019-05-16 15:13 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +    public void testEncryptSHAStringString() throws Exception {
Are all of the `throws Exception`s needed? If so, could they throw something more specific?

2019-05-16 15:13 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo", "SHA-1"));
Add test with `SHA-256`

2019-05-16 15:13 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        Assert.assertEquals("cDeAcZjCKn0rCAc3HXY3eahP388=", retval);
Instead of base64 encoding these bytes, you could just use `assertArrayEquals(new byte[]{...})`, there should be 20 bytes in the array.

2019-05-16 15:13 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo", "SHA-1"));
Also add test that hashes something other than `foo`

2019-05-16 15:13 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo"));
Add test for a non-empty string other than `foo`

2019-05-16 16:30 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo", "SHA-1"));
Done

2019-05-16 16:30 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo", "SHA-1"));
Done

2019-05-16 16:30 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +    public void testEncryptSHAStringString() throws Exception {
Done

2019-05-16 16:30 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                SHA.encryptSHA("foo"));
Done.. used bar as well

2019-05-16 16:38 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        Assert.assertEquals("cDeAcZjCKn0rCAc3HXY3eahP388=", retval);
Done

2019-05-16 16:58 UTC, freddytuxworth approved these changes

2019-05-16 16:58 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        Assert.assertEquals("62cdb7020ff920e5aa642c3d4066950dd1f01f4d",
Might be cleaner to move all of the SHA results to class static variables at the top, like
```
private static final String SHA_256_foo = "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae";
private static final String SHA_1_bar = "...
```
and then reference them in the code. Will reduce line overruns also.

2019-05-16 17:30 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +        Assert.assertEquals("62cdb7020ff920e5aa642c3d4066950dd1f01f4d",
Done

2019-05-16 17:37 UTC, freddytuxworth approved these changes

2019-05-17 13:54 UTC, petersear requested changes

2019-05-17 13:54 UTC, petersear commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                , 55, 29, 118, 55, 121, -88, 79, -33, -49};
The line-break should be after the comma rather than starting a line with ", "

2019-05-17 14:05 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                , 55, 29, 118, 55, 121, -88, 79, -33, -49};
.... I pushed this for an external PR today morning

2019-05-17 14:15 UTC, freddytuxworth commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                , 55, 29, 118, 55, 121, -88, 79, -33, -49};
You can still change it, the PR will change too

2019-05-17 14:19 UTC, Braavos96 commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                , 55, 29, 118, 55, 121, -88, 79, -33, -49};
Done

2019-05-17 14:27 UTC, petersear commented on admin-common/src/test/java/com/lrs/common/utils/encrypt/SHATest.java
> +                , 55, 29, 118, 55, 121, -88, 79, -33, -49};
I'd approved before this version of the changes was made. I caught that when going over one last time after other comments had been resolved.

2019-05-17 14:27 UTC, petersear approved these changes

2019-07-11 08:45 UTC, closed without merging